# Generated by Django 5.0.2 on 2024-04-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuser',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='uploads/signature', verbose_name='Подпись'),
        ),
    ]
