# Generated by Django 5.0.2 on 2024-02-16 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='defuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='defuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия сотрудника'),
        ),
        migrations.AlterField(
            model_name='defuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='defuser',
            name='position',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.position', verbose_name='Должность'),
        ),
    ]
