# Generated by Django 5.0.2 on 2024-02-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_defuser_email_alter_defuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='defuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя сотрудника'),
        ),
        migrations.AlterField(
            model_name='defuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия сотрудника'),
        ),
        migrations.AlterField(
            model_name='defuser',
            name='position',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='accounts.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название отдела'),
        ),
    ]
