# Generated by Django 5.0.2 on 2024-05-11 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_defuser_position_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defuser',
            name='position',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.position', verbose_name='Должность'),
        ),
    ]
