# Generated by Django 5.0.2 on 2024-05-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_defuser_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
