# Generated by Django 5.0.2 on 2024-02-19 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_defuser_email_alter_defuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name=''),
        ),
    ]
