# Generated by Django 5.0.2 on 2024-05-11 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_defuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defuser',
            name='position',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.department', verbose_name='Отдел'),
        ),
    ]
