# Generated by Django 5.0.2 on 2024-05-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_defuser_position_alter_position_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defuser',
            options={'permissions': [('chief_edit_tasks', 'Могут редактировать все задачи')]},
        ),
    ]
