# Generated by Django 5.0.2 on 2024-02-21 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_defuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defuser',
            name='position',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.position', verbose_name='Должность'),
        ),
    ]
