# Generated by Django 5.0.2 on 2024-02-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_defuser_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defuser',
            name='department',
        ),
    ]
