# Generated by Django 5.0.2 on 2024-05-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_defuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
