# Generated by Django 5.0.2 on 2024-03-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_department_name_alter_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuser',
            name='email_password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Пароль почты'),
        ),
    ]
