# Generated by Django 5.0.2 on 2024-03-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_department_name_alter_position_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defuser',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='defuser',
            name='email_password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Пароль от почтового ящика'),
        ),
        migrations.AlterField(
            model_name='defuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=30, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
