# Generated by Django 5.0.2 on 2024-05-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_defuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defuser',
            name='email_password',
        ),
    ]
