# Generated by Django 5.0.2 on 2024-03-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_defuser_patronymic_defuser_email_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defuser',
            name='email_password',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Пароль от почтового ящика'),
        ),
    ]
