# Generated by Django 5.0.2 on 2024-03-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_defuser_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defuser',
            name='email_password',
            field=models.BinaryField(blank=True, max_length=5000, null=True, verbose_name='Пароль от почтового ящика'),
        ),
    ]
