# Generated by Django 5.0.2 on 2024-03-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_defuser_email_password_alter_defuser_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defuser',
            name='email_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль почты'),
        ),
    ]
