# Generated by Django 5.0.2 on 2024-03-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_defuser_email_password'),
        ('accounts', '0010_alter_defuser_email_password'),
    ]

    operations = [
    ]
