# Generated by Django 5.0.2 on 2024-03-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_defuser_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defuser',
            name='email_password',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Пароль от почтового ящика'),
        ),
    ]
