# Generated by Django 5.0.2 on 2024-03-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_defuser_email_password_alter_defuser_position'),
        ('accounts', '0011_alter_defuser_email_password'),
        ('accounts', '0012_alter_defuser_position'),
    ]

    operations = [
    ]
