# Generated by Django 5.0.2 on 2024-03-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_defuser_email_password_alter_defuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuser',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='uploads/signature', verbose_name='Подпись'),
        ),
    ]
