# Generated by Django 5.0.2 on 2024-02-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(max_length=2500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('Accepted', 'Принятая'), ('Not accepted', 'Не принятая'), ('At work', 'В работе'), ('Suspended', 'Приостановлена')], default='Новая', max_length=30, verbose_name='Статус'),
        ),
    ]
