# Generated by Django 5.0.2 on 2024-02-19 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_defuser_email_alter_defuser_first_name_and_more'),
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='task',
            new_name='subtask',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='priority',
            name='task',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='destination_to',
        ),
        migrations.RemoveField(
            model_name='status',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='status',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='destination_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
        migrations.AddField(
            model_name='proposal',
            name='destination_to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='На какой отдел заявка'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='destination_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='На какого сотрудника заявка'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.priority', verbose_name='Приоритет заявки'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Приступить к заявке'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.status', verbose_name='Статус заявки'),
        ),
        migrations.AddField(
            model_name='task',
            name='destination_to_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='На какой отдел задача'),
        ),
        migrations.AddField(
            model_name='task',
            name='destination_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='На какого сотрудника задача'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.priority', verbose_name='Приоритет задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Приступить к задаче'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.status', verbose_name='Статус задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='webapp.task', verbose_name='Подзадача'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи'),
        ),
    ]
