# Generated by Django 5.0.2 on 2024-04-13 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_file_checklist_historicalfile_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='webapp.checklist', verbose_name='Чеклист'),
        ),
    ]
