# Generated by Django 5.0.2 on 2024-05-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_comment_author_alter_comment_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('chief_edit_tasks', 'Может редактировать задачи своего отдела')]},
        ),
    ]
