# Generated by Django 5.0.2 on 2024-02-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_task_proposal_subtask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Files/', verbose_name='Файлы')),
            ],
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='subtask',
            new_name='parent_task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='subtask',
            new_name='parent_task',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.file', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.file', verbose_name='Файлы'),
        ),
    ]
