# Generated by Django 5.0.2 on 2024-04-06 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_file_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='webapp.checklist', verbose_name='Чеклист'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='checklist',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapp.checklist', verbose_name='Чеклист'),
        ),
    ]
