# Generated by Django 5.0.2 on 2024-04-06 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_file_checklist_historicalfile_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='file_to_sign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapp.file', verbose_name='Файл для подписи'),
        ),
        migrations.AddField(
            model_name='task',
            name='file_to_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sign_task', to='webapp.file', verbose_name='Файл для подписи'),
        ),
    ]
