# Generated by Django 5.0.2 on 2024-02-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_file_rename_subtask_proposal_parent_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user_docs', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='done_at',
            field=models.DateTimeField(verbose_name='Время завершения заявки'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения задачи'),
        ),
    ]
