# Generated by Django 5.0.2 on 2024-04-06 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_historicaltask_file_to_sign_task_file_to_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file_to_sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_task', to='webapp.file', verbose_name='Файл для подписи'),
        ),
    ]
