# Generated by Django 5.0.2 on 2024-04-14 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_filesignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='parent_task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='webapp.task', verbose_name='Связанная задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='webapp.task', verbose_name='Связанная задача'),
        ),
    ]
