# Generated by Django 5.0.2 on 2024-02-27 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_proposal_files_remove_task_files_file_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Тип')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='proposal',
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.type', verbose_name='Тип'),
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
