# Generated by Django 5.0.2 on 2024-05-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_historicaltask_parent_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/user_docs', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Файл'),
        ),
    ]
