# Generated by Django 5.0.2 on 2024-02-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_type_remove_comment_proposal_task_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Файл'),
        ),
    ]
