# Generated by Django 5.0.2 on 2024-03-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_file_file_alter_file_task_alter_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Статус задачи/заявки'),
        ),
    ]
