# Generated by Django 5.0.2 on 2024-03-07 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_checklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='user',
        ),
        migrations.AddField(
            model_name='checklist',
            name='user',
            field=models.ManyToManyField(related_name='checklists', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
