# Generated by Django 5.0.2 on 2024-03-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_checklist_user_checklist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='user',
            new_name='users',
        ),
    ]
