# Generated by Django 5.0.2 on 2024-03-20 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_defuser_position'),
        ('webapp', '0014_rename_user_checklist_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=250, verbose_name='Физическое расположение договора')),
            ],
        ),
        migrations.CreateModel(
            name='InOutMailsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='InOutMailsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Файлы'),
        ),
        migrations.CreateModel(
            name='CompaniesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=250, verbose_name='Код компании')),
                ('company_name', models.CharField(max_length=250, verbose_name='Назыание компании')),
                ('company_inn', models.CharField(blank=True, max_length=250, null=True, verbose_name='ИНН Компании')),
                ('contract_with_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.file', verbose_name='Договор с компанией')),
            ],
        ),
        migrations.CreateModel(
            name='ContractRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_contract_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Порядковый номер входяшего документа')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание документа')),
                ('consultion_date', models.DateField(blank=True, null=True, verbose_name='Дата заключения договора')),
                ('scan_copy', models.BooleanField(default=False, verbose_name='Наличие отсканированной копии')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.companieslist', verbose_name='Компания')),
                ('contract_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.contractlocation', verbose_name='Физическое расположение договора')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.file', verbose_name='Вложение')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='InOutMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_number', models.CharField(auto_created=True, blank=True, max_length=250, null=True, verbose_name='Порядковый номер документа')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата/Время регистрации документа')),
                ('input_mail_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер исходящего письма отправителя')),
                ('sender_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Наименование отправителя')),
                ('mail_description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Тема сообщения')),
                ('pages_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество страниц')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.file', verbose_name='Вложение')),
                ('initiator_of_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор исходящего письма')),
                ('responsible_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='Ответственный отдел')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.position', verbose_name='Ответственный сотрудник')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.inoutmailsstatus', verbose_name='Статус письма')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.inoutmailstype', verbose_name='Тип письма')),
            ],
        ),
    ]
