# Generated by Django 5.0.2 on 2024-03-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_historicaltask_start_date_and_more'),
        ('webapp', '0016_alter_task_author_alter_task_parent_task_and_more'),
    ]

    operations = [
    ]
