# Generated by Django 5.0.2 on 2024-04-20 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=250, verbose_name='Физическое расположение договора')),
            ],
        ),
        migrations.CreateModel(
            name='InOutMailsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='CompaniesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=250, verbose_name='Код компании')),
                ('company_name', models.CharField(max_length=250, verbose_name='Назыание компании')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/companies/', verbose_name='Вложение')),
                ('company_inn', models.CharField(blank=True, max_length=250, null=True, verbose_name='ИНН Компании')),
                ('contract_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretarial_work_app.contractlocation', verbose_name='Физическое расположение документа')),
            ],
        ),
        migrations.CreateModel(
            name='ContractRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_auto_number', models.IntegerField(auto_created=True, blank=True, null=True, verbose_name='')),
                ('input_contract_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Порядковый номер входяшего документа')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание документа')),
                ('consultion_date', models.DateField(blank=True, null=True, verbose_name='Дата заключения договора')),
                ('scan_copy', models.BooleanField(default=False, verbose_name='Наличие отсканированной копии')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/contracts/', verbose_name='Вложение')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='secretarial_work_app.companieslist', verbose_name='Компания')),
                ('contract_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretarial_work_app.contractlocation', verbose_name='Физическое расположение договора')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='InMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_mail_number', models.CharField(max_length=20, verbose_name='Входящий № документа')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('mail_number', models.CharField(max_length=20, verbose_name='№ номер поступившего документа')),
                ('sender', models.CharField(max_length=100, verbose_name='От кого поступило сообщение')),
                ('description', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Краткое описание')),
                ('pages_count', models.CharField(blank=True, max_length=20, null=True, verbose_name='Кол-во страниц')),
                ('output_mail_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер исходящего документа')),
                ('scan', models.CharField(max_length=10, verbose_name='Наличие скани копии')),
                ('comments', models.TextField(blank=True, max_length=1500, null=True, verbose_name='Коментарии')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/in_mails/', verbose_name='Вложение')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кому передан на исполнение')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretarial_work_app.inoutmailsstatus', verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='OutMails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_mail_number', models.CharField(max_length=20, verbose_name='Исходящий № документа')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('receiver', models.CharField(max_length=100, verbose_name='Кому адресован документ')),
                ('description', models.TextField(blank=True, max_length='1500', null=True, verbose_name='Краткое описание')),
                ('pages_count', models.CharField(blank=True, max_length=10, null=True, verbose_name='Количество страниц')),
                ('input_mail_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер входящего документа')),
                ('scan', models.CharField(max_length=10, verbose_name='Наличие скан копии')),
                ('comments', models.TextField(blank=True, max_length='1500', null=True, verbose_name='Комментарии')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/out_mails/', verbose_name='Вложение')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretarial_work_app.inoutmailsstatus', verbose_name='Статус')),
            ],
        ),
    ]
