# Generated by Django 5.0.2 on 2024-04-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarial_work_app', '0002_alter_inmails_scan_alter_inmails_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companieslist',
            name='company_name',
            field=models.CharField(max_length=250, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='inmails',
            name='scan',
            field=models.BooleanField(default=False, verbose_name='Наличие скан копии'),
        ),
        migrations.AlterField(
            model_name='outmails',
            name='scan',
            field=models.BooleanField(default=False, verbose_name='Наличие скан копии'),
        ),
    ]
