# Generated by Django 5.0.2 on 2024-04-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarial_work_app', '0003_alter_companieslist_company_name_alter_inmails_scan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractregistry',
            name='scan_copy',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Наличие отсканированной копии'),
        ),
        migrations.AlterField(
            model_name='inmails',
            name='scan',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Наличие скан копии'),
        ),
        migrations.AlterField(
            model_name='outmails',
            name='scan',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Наличие скан копии'),
        ),
    ]
