# Generated by Django 5.0.2 on 2024-04-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarial_work_app', '0004_alter_contractregistry_scan_copy_alter_inmails_scan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/contracts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contractregistry',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='contractregistry',
            name='scan_copy',
            field=models.BooleanField(choices=[(True, 'Есть'), (False, 'Нет')], default=False, verbose_name='Наличие отсканированной копии'),
        ),
        migrations.AlterField(
            model_name='inmails',
            name='scan',
            field=models.BooleanField(choices=[(True, 'Есть'), (False, 'Нет')], default=False, verbose_name='Наличие скан копии'),
        ),
        migrations.AlterField(
            model_name='outmails',
            name='scan',
            field=models.BooleanField(choices=[(True, 'Есть'), (False, 'Нет')], default=False, verbose_name='Наличие скан копии'),
        ),
        migrations.AddField(
            model_name='contractregistry',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='secretarial_work_app.attachment'),
        ),
    ]
