# Generated by Django 5.0.2 on 2024-04-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarial_work_app', '0005_attachment_remove_contractregistry_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='uploads/contracts/', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='contractregistry',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='secretarial_work_app.attachment', verbose_name='Вложения'),
        ),
    ]
