# Generated by Django 5.0.2 on 2024-04-25 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretarial_work_app', '0006_alter_attachment_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractregistry',
            name='scan_copy',
        ),
        migrations.RemoveField(
            model_name='inmails',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='outmails',
            name='scan',
        ),
    ]
