# Generated by Django 5.0.2 on 2024-05-11 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarial_work_app', '0008_alter_contractregistry_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companieslist',
            name='contract_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='secretarial_work_app.contractlocation', verbose_name='Физическое расположение документа'),
        ),
        migrations.AlterField(
            model_name='contractregistry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secretarial_work_app.companieslist', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='contractregistry',
            name='contract_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='secretarial_work_app.contractlocation', verbose_name='Физическое расположение договора'),
        ),
        migrations.AlterField(
            model_name='contractregistry',
            name='responsible_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный сотрудник'),
        ),
        migrations.AlterField(
            model_name='inmails',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Кому передан на исполнение'),
        ),
        migrations.AlterField(
            model_name='inmails',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='secretarial_work_app.inoutmailsstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='outmails',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='outmails',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='secretarial_work_app.inoutmailsstatus', verbose_name='Статус'),
        ),
    ]
